model_list:
  - model_name: mistral ### RECEIVED MODEL NAME ###
    litellm_params: # all params accepted by litellm.completion() - https://docs.litellm.ai/docs/completion/input
      model: ollama/mistral:latest ### MODEL NAME sent to `litellm.completion()` ###
      api_base: localhost:11434
      api_key: "" # does os.getenv("AZURE_API_KEY_EU")
      rpm: 6      # [OPTIONAL] Rate limit for this deployment: in requests per minute (rpm)
  - model_name: llama ### RECEIVED MODEL NAME ###
    litellm_params: # all params accepted by litellm.completion() - https://docs.litellm.ai/docs/completion/input
      model: ollama/llama3.1 ### MODEL NAME sent to `litellm.completion()` ###
      api_base: localhost:11434
      api_key: "" # does os.getenv("AZURE_API_KEY_EU")
      rpm: 6      # [OPTIONAL] Rate limit for this deployment: in requests per minute (rpm)
litellm_settings:
  ssl_verify: false
